#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8              \
    bottom_padding               8              \
    left_padding                 8              \
    right_padding                8              \
    window_gap                   8              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Disable specific apps
yabai -m rule --add app="^Emacs$" manage=on
yabai -m rule --add app-"^Firefox$" manage=on
yabai -m rule --add app="^Karabiner-Elements$" manage=on

yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add title="^Preferences" manage=off
yabai -m rule --add title="^Settings" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Finder$" manage=off

yabai -m rule --add path="/Applications/东方财富领先版.app/Contents/MacOS/东方财富领先版" manage=off


echo "yabai configuration loaded.."
